service: lambda-helloworld
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev

functions:
  hello:
    handler: handler.helloWorld
    events:
      - http:
          path: helloWorld
          method: get
          cors: true

plugins:
  - serverless-offline
